/**
 * Nederlandse biografische verrijking voor heiligen die ook in Orthodox Saint Finder voorkomen.
 * De teksten zijn eigen Nederlandse samenvattingen op basis van de daar vermelde feiten.
 * Ontbrekende of onzekere gegevens worden bewust niet aangevuld.
 */
export interface SaintEnrichment {
  aliases: string[];
  leven: string;
  rang?: string;
  regio?: string;
  eeuw?: string;
  bronUrl: string;
}

export const SAINT_ENRICHMENT: SaintEnrichment[] = [
  {aliases:['basilius de grote','basil the great'],rang:'Hiërarch',regio:'Klein-Azië',eeuw:'4e eeuw',bronUrl:'https://orthodoxsaintfinder.com/saint/OS-0021/',leven:'De heilige Basilius de Grote (ca. 329–379) was aartsbisschop van Caesarea in Cappadocië en behoort tot de grote kerkvaders. Na een grondige opleiding koos hij voor het ascetische leven en bestudeerde hij kloostergemeenschappen in Egypte, Palestina, Syrië en Mesopotamië. Als bisschop verdedigde hij het geloof van Nicea en schreef hij uitvoerig over de Heilige Geest. Ook organiseerde hij op grote schaal zorg voor armen, reizigers en zieken. Zijn regels voor het gemeenschappelijke kloosterleven kregen blijvende invloed in de Orthodoxe Kerk. De Goddelijke Liturgie die zijn naam draagt wordt nog altijd op verschillende belangrijke dagen van het kerkelijk jaar gevierd.'},
  {aliases:['martelaar basilius van ancyra','basil of ancyra'],rang:'Martelaar en priester',regio:'Klein-Azië',eeuw:'4e eeuw',bronUrl:'https://orthodoxsaintfinder.com/saint/OS-0373/',leven:'De heilige martelaar Basilius was priester in Ancyra. Tijdens de regering van keizer Julianus de Afvallige verzette hij zich openlijk tegen de herleving van het heidendom. Hij bleef Christus belijden ondanks vervolging en zware martelingen en werd uiteindelijk ter dood gebracht omdat hij weigerde zijn geloof te verloochenen.'},
  {aliases:['h. fanchea van killeany','fanchea','fanchea van rossory'],rang:'Eerbiedwaardige abdis',regio:'Ierland',eeuw:'6e eeuw',bronUrl:'https://orthodoxsaintfinder.com/saint/OS-2814/',leven:'De heilige Fanchea was een Ierse abdis die rond het begin van de zesde eeuw leefde. Zij wordt vooral herinnerd als de zuster en geestelijke gids van de heilige Enda van Aran, die zij aanspoorde het krijgersleven achter zich te laten en het monastieke leven te omarmen. Zij stichtte en leidde een vrouwengemeenschap te Rossory aan Lough Erne. De verhalen over haar leven zijn vooral in latere hagiografische traditie bewaard en moeten daarom met die historische beperking gelezen worden.'},
  {aliases:['serafim van sarov','seraphim of sarov'],rang:'Eerbiedwaardige',regio:'Rusland',eeuw:'19e eeuw',bronUrl:'https://orthodoxsaintfinder.com/saint/OS-0043/',leven:'De heilige Serafim van Sarov (1754–1833) was een Russische monnik, kluizenaar en geestelijke vader. Hij leefde jarenlang in afzondering, gebed en ascese en werd later door vele mensen gezocht om zijn geestelijke raad. Zijn leven werd gekenmerkt door innerlijke vrede, vreugde in Christus en het gebed om de Heilige Geest. Hij is een van de meest geliefde Russische heiligen en wordt vaak herinnerd om zijn begroeting: “Mijn vreugde, Christus is verrezen!”'},
  {aliases:['silvester van rome','sylvester pope of rome','h. sylvester'],rang:'Hiërarch',regio:'Rome',eeuw:'4e eeuw',bronUrl:'https://orthodoxsaintfinder.com/saint/OS-0376/',leven:'De heilige Silvester was bisschop van Rome in de tijd van keizer Constantijn de Grote, toen na de zware vervolgingen een periode van vrede voor de Kerk aanbrak. Zijn episcopaat viel samen met het Eerste Oecumenische Concilie van Nicea in 325. In de kerkelijke overlevering wordt hij herinnerd als een herder van de Kerk in deze belangrijke overgangstijd.'},
  {aliases:['h. genevieve van paris','genevieve van paris'],rang:'Eerbiedwaardige',regio:'Gallië / Frankrijk',eeuw:'5e eeuw',bronUrl:'https://orthodoxsaintfinder.com/saint/OS-0081/',leven:'De heilige Geneviève van Parijs was een vijfde-eeuwse maagd en ascete uit Gallië. Vanaf jonge leeftijd wijdde zij haar leven aan Christus. Zij werd bekend om haar gebed, vasten, zorg voor armen en haar standvastigheid in tijden van gevaar. De traditie van Parijs bewaart in het bijzonder de herinnering aan haar gebed en moed tijdens bedreigingen van de stad.'},
  {aliases:['profeet malachias','prophet malachi'],rang:'Profeet',regio:'Heilig Land',eeuw:'Oude Testament',bronUrl:'https://orthodoxsaintfinder.com/saint/OS-0381/',leven:'De heilige profeet Maleachi behoort tot de laatste profeten van het Oude Testament. Zijn profetie roept het volk op tot trouw aan God en spreekt over de komst van de bode die de weg voor de Heer zal bereiden. De christelijke traditie herkent hierin een voorafbeelding van de heilige Johannes de Voorloper en van de komst van Christus, de Zon der gerechtigheid.'},
  {aliases:['rechtvaardige juliana van lazarevo','juliana of lazarevo'],rang:'Rechtvaardige',regio:'Rusland',eeuw:'17e eeuw',bronUrl:'https://orthodoxsaintfinder.com/saint/OS-0378/',leven:'De rechtvaardige Juliana van Lazarevo leefde haar heiligheid midden in huwelijk, gezin en huishoudelijke verantwoordelijkheid. Zij stond bekend om haar grote zorg voor armen en zieken. In perioden van hongersnood deelde zij haar bezit uit om anderen te voeden. Haar leven laat zien hoe gebed, barmhartigheid en zelfverloochening ook binnen het gewone gezinsleven een weg tot heiligheid kunnen vormen.'},
  {aliases:['eerbiedwaardige sylvester van de kievse grotten','sylvester of the kiev caves'],rang:'Eerbiedwaardige monnik',regio:'Oekraïne',eeuw:'12e eeuw',bronUrl:'https://orthodoxsaintfinder.com/saint/OS-0379/',leven:'De eerbiedwaardige Sylvester was monnik van het Holenklooster van Kiev. De overlevering bewaart hem als een man van gehoorzaamheid en voortdurend gebed. Hij behoort tot de grote gemeenschap van monniken van de Kievse Grotten wier ascetische leven een blijvende plaats kreeg in de Slavisch-orthodoxe traditie.'},
  {aliases:['eerbiedwaardige euthymius (taqaishvili) de man van god van tbilisi','euthymius takaishvili','euthymius taqaishvili'],rang:'Rechtvaardige',regio:'Georgië',eeuw:'20e eeuw',bronUrl:'https://orthodoxsaintfinder.com/saint/OS-0380/',leven:'De heilige Euthymius (Ekvtime) Taqaishvili was een Georgische historicus en behoeder van het culturele en kerkelijke erfgoed van zijn land. Tijdens revolutie en ballingschap waakte hij over een grote verzameling nationale schatten en weigerde hij deze voor persoonlijk voordeel prijs te geven. Hij leefde zelf eenvoudig en in armoede en werd vanwege zijn trouw en onbaatzuchtigheid “de Man van God” genoemd.'},
  {aliases:['martelaar gordius te caesarea in cappadocie','martelaar gordius te caesarea','gordius of caesarea'],rang:'Martelaar',regio:'Klein-Azië',eeuw:'4e eeuw',bronUrl:'https://orthodoxsaintfinder.com/saint/OS-0382/',leven:'De heilige Gordius was een centurio uit Caesarea in Cappadocië. Tijdens de vervolging van christenen trok hij zich eerst terug in de woestijn. Later keerde hij vrijwillig naar de stad terug en beleed hij Christus openlijk in het openbaar. Voor deze belijdenis werd hij ter dood gebracht en als martelaar vereerd.'},
  {aliases:['nieuwe martelaar onuphrius manassias van gabrovo en hilandar monastery','onuphrius of gabrovo'],rang:'Nieuwe martelaar',regio:'Bulgarije / Athos',eeuw:'19e eeuw',bronUrl:'https://orthodoxsaintfinder.com/saint/OS-0385/',leven:'De nieuwe martelaar Onuphrius was afkomstig uit de omgeving van Gabrovo en werd monnik van het Hilandarklooster op de Heilige Berg Athos. Hij legde later openlijk belijdenis van zijn christelijk geloof af tegenover de Ottomaanse autoriteiten. In 1818 werd hij op Chios onthoofd en ontving hij de martelaarskroon.'}
  ,{aliases:['matthias','apostel matthias'],rang:'Apostel',regio:'Heilig Land',eeuw:'1e eeuw',bronUrl:'https://orthodoxsaintfinder.com/saint/OS-1676/',leven:'De heilige apostel Matthias werd na de Hemelvaart door het lot gekozen om de plaats van Judas onder de Twaalf in te nemen. Volgens de orthodoxe overlevering behoorde hij tot de leerlingen die Christus vanaf het begin volgden. Na Pinksteren verkondigde hij het Evangelie en wordt hij in de Kerk vereerd als een van de heilige Twaalf Apostelen.'},
  {aliases:['martelaar sabinus abibus van egypte','sabinus van egypte'],rang:'Martelaar',regio:'Egypte',eeuw:'3e–4e eeuw',bronUrl:'https://orthodoxsaintfinder.com/saint/OS-0817/',leven:'De heilige martelaar Sabinus was een christen uit Egypte en bestuurder van Hermopolis in de tijd van de vervolgingen onder Diocletianus. Hij trok zich met andere gelovigen terug toen de vervolging heviger werd, maar zijn schuilplaats werd verraden. Na martelingen weigerde hij Christus te verloochenen en werd hij in de Nijl verdronken. In verschillende bronnen komt hij ook voor onder de namen Abibus en Phanas.'}
];

function norm(s:string){return s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[.(),]/g,'').replace(/\s+/g,' ').trim()}
export function getSaintEnrichment(name:string): SaintEnrichment | undefined {
  const n=norm(name);
  return SAINT_ENRICHMENT.find(e=>e.aliases.some(a=>{const x=norm(a);return n===x || (x.length>7 && (n.includes(x)||x.includes(n)))}));
}
