/**
 * Verbetert de namen en titels van heiligen en gedachtenissen.
 *
 * De heiligendatabase is gemaakt uit een Engelse kalender met een woord-voor-woord-vertaling, waardoor er
 * mengvormen ontstonden zoals "Sunday before de Universal Elevation van de Kostbare en Life-Creating Cross van
 * de Lord". Deze functie zet de vaste patronen (Synaxis, Icon, Translation of relics, Forefeast, ...) en de
 * losse Engelse woorden om in gewoon Nederlands. Namen die al Nederlands zijn blijven ongewijzigd.
 */

type Regel = [RegExp, string | ((substring: string, ...args: string[]) => string)];

const ruimOp = (s: string) => s.replace(/\s{2,}/g, ' ').replace(/\s+([.,;:)])/g, '$1').trim();

// Vertaling van Engelse titels en bijnamen van icoontjes.
const TITELS: Regel[] = [
  [/Kazan "Of de Seven Lakes" Icon/g, 'Kazan-icoon „Van de Zeven Meren”'],
  [/Kursk "Sign" Icon \((\d+)\) Icoon van de Moeder Gods/g, 'Koersk-icoon „Van het Teken” ($1) van de Moeder Gods'],
  [/Kursk "Sign" Icon/g, 'Koersk-icoon „Van het Teken”'],
  [/Of de Sign/g, 'Van het Teken'],
  [/Of de Four Days/g, 'Van de Vier Dagen'],
  [/"?The Word Was Made Flesh"?/g, 'Het Woord is vlees geworden'],
  [/Surety van Sinners/g, 'Borg der zondaren'],
  [/Of de Passion/g, 'Van het Lijden'],
  [/It is Truly Meet/g, 'Het is waarlijk billijk'],
  [/Of de Three Hands/g, 'Van de Drie Handen'],
  [/The Quick Hearer van de berg Athos/g, 'De Snelle Verhoorster van de berg Athos'],
  [/She Who is Quick to Hear/g, 'Zij die snel verhoort'],
  [/Of de Don\b/g, 'Van de Don'],
  [/Of de Akathist/g, 'Van de Akathist'],
  [/O All-Hymned Mother/g, 'O alomgeprezen Moeder'],
  [/She Who Ripens de Grain/g, 'Zij die het graan doet rijpen'],
  [/The Joy van All Who Sorrow/g, 'De Vreugde van allen die treuren'],
  [/The Unburnt Bush/g, 'De Onverbrandbare Braamstruik'],
  [/Everlasting Hoop/g, 'Eeuwige Hoop'],
  [/Of de Seven Lakes/g, 'Van de Zeven Meren'],
  [/At de Source/g, 'Bij de Bron'],
  [/New Light/g, 'Nieuw Licht'],
  [/Triumph van Holy Moeder Gods/g, 'Zegepraal van de heilige Moeder Gods'],
  [/Holy Night/g, 'Heilige Nacht'],
];

// Vaste uitdrukkingen (specifiek vóór algemeen).
const FRASEN: Regel[] = [
  [/Apparition van de Sign van de Kostbare Cross over Jerusalem( in 351 A\.D\.)?/g, 'Verschijning van het Teken van het Kostbare Kruis boven Jeruzalem$1'],
  [/Synaxis van All Holy Russian Sovereigns Commemorated on Athos\./g, 'Synaxis van alle heilige Russische Vorsten die op de Athos worden herdacht.'],
  [/Synaxis van Russian Saints glorified on Moscow Councils/g, 'Synaxis van de Russische heiligen die op de Moskouse Concilies heilig werden verklaard'],
  [/Synaxis van All Saints Who Shone Forth in de Spanish en Portuguese Lands/g, 'Synaxis van alle heiligen die in de Spaanse en Portugese landen hebben geschitterd'],
  [/Synaxis van (Novgorod|Hilandar) Hierarchs/g, 'Synaxis van de Hiërarchen van $1'],
  [/Synaxis van (\p{Lu}[\p{L}-]+) Saints$/gu, 'Synaxis van de heiligen van $1'],
  [/Kiev-Pechersk Far Caves/g, 'Verre Grotten van Kiev-Petsjersk'],
  [/van de Kievan Caves (?:Monastery|Klooster)/g, 'van het Kievse Grottenklooster'],
  [/Pskov Caves Icon/g, 'Pskov-Grotten-icoon'],
  [/Pskov Caves/g, 'Pskov-Grotten'],
  [/Optina Elders/g, 'Optina-ouderlingen'],
  [/Klarjeti Wilderness/g, 'Klarjeti-woestijn'],
  [/van Stolben Island/g, 'van het eiland Stolben'],
  [/Stolben Island/g, 'het eiland Stolben'],
  [/de slain Crown Vorst/g, 'de vermoorde Kroonprins'],
  [/de Kostbare Robe van de Lord/g, 'het Kostbare Gewaad van de Heer'],
  [/Nederlegging van Belt van de (?:Allerheiligste|Most Holy)/g, 'Nederlegging van de Gordel van de Allerheiligste'],
  [/Nederlegging van (?:de )?Kostbare Robe van de Lord/g, 'Nederlegging van het Kostbare Gewaad van de Heer'],
  [/Nederlegging van (?:de )?Kostbare Robe/g, 'Nederlegging van het Kostbare Gewaad'],
  [/Miracle van de Pillar met het Gewaad van de (?:Lord|Heer) onder it/g, 'Wonder van de Pilaar met het Gewaad van de Heer, eronder'],
  [/Translation uit Malta to Gatchina van a part van de Life-Creating Cross van de Lord/g, 'Overbrenging van een deel van het Levenschenkende Kruis van de Heer uit Malta naar Gatchina'],
  [/Feast to de All-Merciful Saviour en de Most Holy/g, 'Feest van de Alomontfermende Heiland en de Allerheiligste'],
  [/Appearance van de Light-Painted image/g, 'Verschijning van het lichtgeschilderde beeld'],
  [/Appearance van de Kolomenskoye Icon/g, 'Verschijning van de Kolomenskoje-icoon'],
  [/\(before heilige baptism ([^)]+)\)/g, '(vóór de heilige doop: $1)'],
  [/\(in heilige baptism ([^)]+)\)/g, '(bij de heilige doop: $1)'],
  [/\(movable holiday on de Trinity Sunday\)/g, '(beweeglijk feest op Drie-eenheidszondag)'],
  [/blind man die confessed Christ en was gemarteld met (.+)$/g, 'de blinde man die Christus beleed en samen met $1 werd gemarteld'],
  [/die geleden during de "Holy Night" in H\. Petersburg/g, 'die tijdens de „Heilige Nacht” in Sint-Petersburg leden'],
  [/die geleden during de "Heilige Nacht" in H\. Petersburg/g, 'die tijdens de „Heilige Nacht” in Sint-Petersburg leden'],
  [/die geleden during de "Heilige Nacht"/g, 'die tijdens de „Heilige Nacht” leden'],
  [/die geleden during de/g, 'die tijdens de'],
  [/te de gate van Eugenius/g, 'bij de Poort van Eugenius'],
  [/te de Klooster/g, 'in het klooster'],
  [/naar de klooster/g, 'naar het klooster'],
  [/Gedachtenis van de [Ww]onder/g, 'Gedachtenis van het wonder'],
  [/Vinding van het relieken/g, 'Vinding van de relieken'],
  [/Veneration van/g, 'Verering van'],
  [/Child-martyr/g, 'Kind-martelaar'],
  [/\bSt Matrona/g, 'H. Matrona'],
  [/H\. Petersburg/g, 'Sint-Petersburg'],
  [/whose relieken repose in de Far Cave/g, 'wier relieken rusten in de Verre Grot'],
  [/whose relieken repose/g, 'wier relieken rusten'],
  [/Synaxis van de Seventy Apostelen: Jakobus de Brother van de Lo'rd/g, 'Synaxis van de Zeventig Apostelen: Jakobus, de Broer van de Heer'],
  [/Jakobus de Brother van de Lord/g, 'Jakobus, de Broer van de Heer'],
  [/Apostelen van de Seventy/g, 'Apostelen van de Zeventig'],
  [/Apostel (Titus|Filippus) van de Seventy/g, 'Apostel $1 van de Zeventig'],
  [/Our Most Holy Lady de Moeder Gods en Ever-Virgin Maria/g, 'onze Allerheiligste Vrouwe, de Moeder Gods en Altijd-Maagd Maria'],
  [/[Oo]ur Lord (?:en )?God (?:en )?Sa(?:viou|vio)r Jesus Christ/g, 'onze Heer, God en Heiland Jezus Christus'],
  [/[Oo]ur Lord (?:en )?God (?:en )?Savior Jesus Christ/g, 'onze Heer, God en Heiland Jezus Christus'],
  [/Our Lord en God en Saviour Jesus Christ/g, 'onze Heer, God en Heiland Jezus Christus'],
  [/[Oo]ur Lord Jesus Christ/g, 'onze Heer Jezus Christus'],
  [/[Oo]ur Lord/g, 'onze Heer'],
  [/Most Holy Moeder Gods/g, 'Allerheiligste Moeder Gods'],
  [/Nativity according to de Flesh van onze Heer/g, 'Geboorte naar het vlees van onze Heer'],
  [/Image Not-Made-By-Hands/g, 'Niet door mensenhanden gemaakt Beeld'],
  [/van de Light-Painted image/g, 'van het lichtgeschilderde beeld'],
  [/Light-Painted image/g, 'lichtgeschilderde beeld'],
  [/Kostbare en Life-Creating Cross/g, 'Kostbare en Levenschenkende Kruis'],
  [/Kostbare en Levengevende Cross/g, 'Kostbare en Levengevende Kruis'],
  [/Kostbare Wood van de Levengevende Cross/g, 'Kostbare Hout van het Levengevende Kruis'],
  [/Kostbare Cross en de Kostbare Nails/g, 'Kostbare Kruis en de Kostbare Nagels'],
  [/Kostbare Chains van de Holy en All-glorious Apostel/g, 'Kostbare Ketenen van de heilige en alomgeprezen Apostel'],
  [/Kostbare Robe/g, 'Kostbare Gewaad'],
  [/\(in de tomb\)/g, '(in het graf)'],
  [/in de Russian Saint Pantelejmon Monastery/g, 'in het Russische Pantelejmon-klooster'],
  [/Belt van de Most Holy/g, 'Gordel van de Allerheiligste'],
  [/Universal Elevation/g, 'Verheffing'],
  [/Exaltation van de Cross/g, 'Verheffing van het Kruis'],
  [/Life-Creating Cross/g, 'Levenschenkende Kruis'],
  [/Life-Giving Trinity/g, 'Levengevende Drie-eenheid'],
  [/Holy en Life-Giving/g, 'Heilige en Levengevende'],
  [/Ever-Virgin/g, 'Altijd-Maagd'],
  [/Sign van de Kostbare Cross over Jerusalem in 351 A\.D\./g, 'Teken van het Kostbare Kruis boven Jeruzalem in 351 n.Chr.'],
  [/Founding van de Church van de Resurrection \(The Holy Sepulchre\)/g, 'Inwijding van de Kerk van de Opstanding (het Heilig Graf)'],
  [/Church New Year\./g, 'Kerkelijk Nieuwjaar.'],
  [/From December 25 till January 5 is a Fast-free period/g, 'Van 25 december tot en met 5 januari is het vastenvrij'],
  [/Parents� Saturday\. Remembrance van de dead\./g, 'Zaterdag van de overledenen.'],
  [/Demetrius \(Parental\) Saturday\. Remembrance van de dead\./g, 'Demetrius-zaterdag (voor de overledenen).'],
  [/Remembrance van all de departed die geleden in de years van persecution for faith in Christ\./g, 'Gedachtenis van allen die in de jaren van vervolging omwille van het geloof in Christus hebben geleden.'],
  [/Beginning van Apostelen' \(Petrus & Paulus\) Fast/g, 'Begin van de Apostelvasten'],
  [/Beginning van de Dormition Fast/g, 'Begin van de Ontslapingsvasten'],
  [/Beginning van Nativity Fast/g, 'Begin van de Geboortevasten'],
  [/Beginning van/g, 'Begin van'],
  [/Fast [Dd]ay/g, 'Vastendag'],
  [/Entire week/g, 'Gehele week'],
  [/Week van Holy Forefathers/g, 'Week van de heilige Voorvaderen'],
  [/Rechtvaardige voorouders van God/g, 'Rechtvaardige Godsvoorvaderen'],
  [/Fifth Ecumenical Council/g, 'Vijfde Oecumenische Concilie'],
  [/Three Hierarchs/g, 'Drie Hiërarchen'],
  [/Three Holy Youths/g, 'Drie heilige Jongelingen'],
  [/other Bodiless Powers/g, 'andere onlichamelijke Machten'],
  [/Holy Nine Children/g, 'Heilige Negen Kinderen'],
  [/Holy Ten Thousand Ascetics/g, 'Heilige Tienduizend Asceten'],
  [/7 Holy Youths \("7 Sleepers"\)/g, '7 Heilige Jongelingen („de 7 Slapers”)'],
  [/7 Holy Youths/g, '7 Heilige Jongelingen'],
  [/Holy Seven Youths/g, 'Heilige Zeven Jongelingen'],
  [/Holy Seven Maccabees/g, 'Heilige Zeven Makkabeeën'],
  [/Eighty Holy Martelaren/g, 'Tachtig Heilige Martelaren'],
  [/Holy Forty Martelaren/g, 'Heilige Veertig Martelaren'],
  [/Holy Forty Maagd-martelaressen/g, 'Heilige Veertig Maagd-martelaressen'],
  [/Holy Martelaared Brothers/g, 'Heilige Gemartelde Broers'],
  [/Holy en Wonderworking Onbaatzuchtigen/g, 'Heilige en Wonderdoende Onbaatzuchtigen'],
  [/Holy Wonderdoeners en Onbaatzuchtigen/g, 'Heilige Wonderdoeners en Onbaatzuchtigen'],
  [/Holy Equals-to-de-Apostelen/g, 'Heilige Gelijk-aan-de-Apostelen'],
  [/Holy gelijk aan de apostelen Great Vorst/g, 'Heilige gelijk aan de apostelen Grootvorst'],
  [/gelijk aan de apostelen Great Vorst/g, 'gelijk aan de apostelen Grootvorst'],
  [/Holy Myrrh-bearer en gelijk aan de apostelen Maria Magdalen/g, 'Heilige Mirredraagster en gelijk aan de apostelen Maria Magdalena'],
  [/Holy Royal Martelaren van Russia: Tsar/g, 'Heilige Koninklijke Martelaren van Rusland: Tsaar'],
  [/Holy 33 Martelaren/g, 'Heilige 33 Martelaren'],
  [/Holy 45 Martelaren/g, 'Heilige 45 Martelaren'],
  [/Holy 362 Martelaren/g, 'Heilige 362 Martelaren'],
  [/Holy 165 Fathers/g, 'Heilige 165 Vaders'],
  [/Holy Vorstin/g, 'Heilige Vorstin'],
  [/Holy Vorst /g, 'Heilige Vorst '],
  [/Holy Princes /g, 'Heilige Vorsten '],
  [/Holy Koningin/g, 'Heilige Koningin'],
  [/Holy Virgin/g, 'Heilige Maagd'],
  [/Holy [Ww]omen/g, 'Heilige vrouwen'],
  [/Holy women/g, 'Heilige vrouwen'],
  [/Holy Passiedrager/g, 'Heilige Passiedrager'],
  [/8 Holy/g, '8 Heilige'],
  [/God-seer/g, 'Godschouwer'],
  [/God-bearing Father/g, 'Godragende Vader'],
  [/Cross-bearer/g, 'Kruisdrager'],
  [/fool-for-Christ/g, 'dwaas om Christus’ wil'],
  [/Myrrh-Streaming/g, 'mirre-vloeiende'],
  [/Myrrh-gusher/g, 'Mirrestromer'],
  [/Myrrh-bearer/g, 'Mirredraagster'],
  [/Miracle-working/g, 'Wonderdoende'],
  [/Wonderworking/g, 'Wonderdoende'],
  [/Weeping/g, 'wenende'],
  [/First-called/g, 'Eerstgeroepen'],
  [/All-Merciful Saviour/g, 'Alomontfermende Heiland'],
  [/All-glorious/g, 'alomgeprezen'],
  [/Great Nieuwe martelaar/g, 'Grote Nieuwe martelaar'],
  [/Great Martelaar/g, 'Grootmartelaar'],
  [/Great Vorst/g, 'Grootvorst'],
  [/New Nieuwe/g, 'Nieuwe'],
  [/New Monnik-martyrs/g, 'Nieuwe monnik-martelaren'],
  [/New Monnik-martyr/gi, 'Nieuwe monnik-martelaar'],
  [/Monnik-martyr/g, 'Monnik-martelaar'],
  [/New Hiero-martyrs/g, 'Nieuwe hiëro-martelaren'],
  [/New Hiero-confessor/g, 'Nieuwe hiëro-belijder'],
  [/New Woman-? ?Priestermartelaar/g, 'Nieuwe priestervrouw-martelares'],
  [/New Maagd-martelares/g, 'Nieuwe maagd-martelares'],
  [/New-Martelaar/g, 'Nieuwe martelaar'],
  [/New Belijder/g, 'Nieuwe belijder'],
  [/van New Ephesus/g, 'van Nieuw-Efeze'],
  [/Translation into Moscow van/g, 'Overbrenging naar Moskou van'],
  [/Translation van (?:de )?(?:Relics|relics|relieken) en garments/g, 'Overbrenging van de relieken en gewaden'],
  [/Translation van de relieken en garments/g, 'Overbrenging van de relieken en gewaden'],
  [/Translation van (?:de )?(?:Relics|relics|relieken)/g, 'Overbrenging van de relieken'],
  [/Translation van de Image/g, 'Overbrenging van het Beeld'],
  [/Translation van Velikoretsky Icon/g, 'Overbrenging van de Velikoretsk-icoon'],
  [/Second Uncovering van de relieken/g, 'Tweede vinding van de relieken'],
  [/Second Uncovering/g, 'Tweede vinding'],
  [/[Uu]ncovering en Overbrenging van de relieken/g, 'Vinding en overbrenging van de relieken'],
  [/[Uu]ncovering van (?:de )?(?:heilige )?(?:Relics|relics|relieken)/g, 'Vinding van de relieken'],
  [/Uncovering van Relics/g, 'Vinding van de relieken'],
  [/[Uu]ncovering van de Kostbare Kruis/g, 'Vinding van het Kostbare Kruis'],
  [/Finding van relieken/g, 'Vinding van de relieken'],
  [/Returning van de relieken/g, 'Terugkeer van de relieken'],
  [/Reverence list van an? /g, 'Kopie van een '],
  [/The Bringing van/g, 'De Binnenbrenging van'],
  [/Bringing van/g, 'Binnenbrenging van'],
  [/The Enthronement van Saint/g, 'De Intronisatie van de heilige'],
  [/Enthronement van Saint/g, 'Intronisatie van de heilige'],
  [/Enthronement/g, 'Intronisatie'],
  [/miraculous renewal van/g, 'wonderbaarlijke vernieuwing van'],
  [/Church van Holy Peace by de Sea/g, 'Kerk van de Heilige Vrede aan zee'],
  [/whose relieken repose in de Far Cave/g, 'wier relieken rusten in de Verre Grot'],
  [/geleden onder de Atheist Yoke/g, 'geleden onder het Atheïstische Juk'],
  [/in memory van Saving van Moskou uit de Invasion van Khan Achmed/g, 'ter gedachtenis aan de redding van Moskou van de invasie van Khan Achmed'],
  [/deliverance van Moskou uit de Invasion van Tamerlane/g, 'bevrijding van Moskou van de invasie van Tamerlan'],
  [/healing van blinded Stefanus by de Icon/g, 'genezing van de verblinde Stefanus door de icoon'],
];

// Vaste voorvoegsels aan het begin van een naam.
const BEGIN: Regel[] = [
  [/^The /, 'De '],
  [/^Forefeast van (?:de )?/, 'Voorfeest van de '],
  [/^Apodosis van (?:de )?/, 'Afscheid van de '],
  [/^Eve van (?:de )?/, 'Vooravond van de '],
  [/^Saturday before (?:de )?/, 'Zaterdag vóór de '],
  [/^Saturday after (?:de )?/, 'Zaterdag na de '],
  [/^Sunday before (?:de )?/, 'Zondag vóór de '],
  [/^Sunday after (?:de )?/, 'Zondag na de '],
  [/^Saturday (?=de )/, 'Zaterdag rond '],
  [/^Remembrance van (?:de )?/, 'Gedachtenis van de '],
  [/^Repose\b/, 'Ontslaping'],
  [/^Glorification\b/, 'Heiligverklaring'],
  [/^Miracle\b/, 'Wonder'],
  [/^Synaxis van All Saints/, 'Synaxis van alle heiligen'],
  [/^Synaxis van all saints/, 'Synaxis van alle heiligen'],
  [/^Synaxis van (?:de )?[Ss]aints van/, 'Synaxis van de heiligen van'],
  [/^Synaxis van (?:de )?[Ss]aints\b/, 'Synaxis van de heiligen'],
];

// Feestnamen (na "van de" / "van").
const FEESTEN: Regel[] = [
  [/Baptism van onze Heer,? God en Heiland Jezus Christus/g, 'Doop van onze Heer, God en Heiland Jezus Christus'],
  [/Theophany/g, 'Theofanie'],
  [/Transfiguration/g, 'Gedaanteverandering'],
  [/Annunciation Icoon/g, 'Boodschap-icoon'],
  [/Annunciation/g, 'Boodschap aan de Moeder Gods'],
  [/Dormition Icoon/g, 'Ontslapingsicoon'],
  [/Dormition Fast/g, 'Ontslapingsvasten'],
  [/Dormition/g, 'Ontslaping van de Moeder Gods'],
  [/Entry van de Allerheiligste Moeder Gods into de Temple/g, 'Intocht van de Allerheiligste Moeder Gods in de Tempel'],
  [/Meeting van onze Heer/g, 'Ontmoeting van de Heer'],
  [/Meeting van/g, 'Ontmoeting van'],
  [/Procession van/g, 'Processie van'],
  [/Nativity/g, 'Geboorte'],
  [/Geboorte van Christ\b/g, 'Geboorte van Christus'],
];

// Losse woorden en categorieën.
const WOORDEN: Regel[] = [
  [/\b(First|Eerste|Second|Third|Fourth|Fifth|Sixth|Seventh|Eighth|Ninth) Ecumenical Council\b/g, '$1 Oecumenisch Concilie'],
  [/\bEcumenical Council\b/g, 'Oecumenisch Concilie'],
  [/\bAll-Russische Kerk Council\b/g, 'Al-Russisch Kerkelijk Concilie'],
  [/\bSecond Oecumenisch\b/g, 'Tweede Oecumenisch'],
  [/\bThird Oecumenisch\b/g, 'Derde Oecumenisch'],
  [/\bFourth Oecumenisch\b/g, 'Vierde Oecumenisch'],
  [/\bFifth Oecumenisch\b/g, 'Vijfde Oecumenisch'],
  [/\bSixth Oecumenisch\b/g, 'Zesde Oecumenisch'],
  [/\bSeventh Oecumenisch\b/g, 'Zevende Oecumenisch'],
  [/\bEerste Oecumenisch\b/g, 'Eerste Oecumenisch'],
  [/\bde Far Caves\b/g, 'de Verre Grotten'],
  [/\bde Near Caves\b/g, 'de Nabije Grotten'],
  [/\bde Oude Caves\b/g, 'de Oude Grotten'],
  [/\bKievan Caves\b/g, 'Kievse Grotten'],
  [/\bCaves\b/g, 'Grotten'],
  [/\bHermitage\b/g, 'Kluizenarij'],
  [/\bSkete\b/g, 'Skite'],
  [/\bLake\b/g, 'Meer'],
  [/\bIsland\b/g, 'Eiland'],
  [/\bRiver\b/g, 'Rivier'],
  [/\bSea\b/g, 'Zee'],
  [/\bde Sea\b/g, 'de Zee'],
  [/\bWhite\b/g, 'Witte'],
  [/\bBlue-Jay\b/g, 'Blauwe Gaai'],
  [/\bGorge-dweller\b/g, 'Kloofbewoner'],
  [/\bEight\b/g, 'Acht'],
  [/\banchorites\b/g, 'kluizenaars'],
  [/\bAscetic\b/g, 'Asceet'],
  [/\bElders\b/g, 'Ouderlingen'],
  [/\bPrinces\b/g, 'Vorsten'],
  [/\bSuffering\b/g, 'Lijden'],
  [/\banother\b/g, 'een andere'],
  [/\bwere\b/g, 'werden'],
  [/\btwo\b/g, 'twee'],
  [/^Return van/g, 'Terugkeer van'],
  [/\bdied\b/g, 'stierven'],
  [/\bhunger\b/g, 'honger'],
  [/\bdrowned\b/g, 'verdronken'],
  [/\bbefore\b/g, 'vóór'],
  [/\bOrthodox Christians\b/g, 'orthodoxe christenen'],
  [/\ball orthodoxe\b/g, 'alle orthodoxe'],
  [/\bEerbiedwaardiges\b/g, 'Eerbiedwaardigen'],
  [/\bGlorious\b/g, 'roemrijke'],
  [/\bSeventy\b/g, 'Zeventig'],
  [/\bTen\b/g, 'Tien'],
  [/\bwhose\b/g, 'wier'],
  [/\btown\b/g, 'stad'],
  [/\bregion\b/g, 'regio'],
  [/\bPillar\b/g, 'Pilaar'],
  [/\bBelorussia\b/g, 'Wit-Rusland'],
  [/\b(in|naar|uit|van) Jordan\b/g, '$1 Jordanië'],
  [/\bde Greek\b/g, 'de Griek'],
  [/\bde Georgian\b/g, 'de Georgiër'],
  [/\bGreek\b/g, 'Griekse'],
  [/\bGeorgian\b/g, 'Georgische'],
  [/\bDalmatian\b/g, 'Dalmatische'],
  [/\bVirgin\b/g, 'Maagd'],
  [/\bslain\b/g, 'vermoord'],
  [/\bMonks\b/g, 'Monniken'],
  [/\bmonks\b/g, 'monniken'],
  [/\bnovices\b/g, 'novicen'],
  [/\bFounder\b/g, 'Stichter'],
  [/\bfounder\b/g, 'stichter'],
  [/\bCathedral\b/g, 'Kathedraal'],
  [/\bMaster-Builders\b/g, 'Bouwmeesters'],
  [/\bLutherans\b/g, 'Lutheranen'],
  [/\bAncient\b/g, 'Oude'],
  [/\bGeneral\b/g, 'Generaal'],
  [/\btransferred\b/g, 'overgebracht'],
  [/\bincorrupt\b/g, 'onvergankelijke'],
  [/\bCustoms Inspector\b/g, 'Douane-inspecteur'],
  [/\bKeeper van de Sacred Vessels\b/g, 'Bewaarder van de Heilige Vaten'],
  [/\bMilk-giver\b/g, 'Melkgeefster'],
  [/\bMt\.? (?=[A-Z])/g, 'Berg '],
  [/\bChannel Islands\b/g, 'Kanaaleilanden'],
  [/\bTwelve\b/g, 'Twaalf'],
  [/\btwelve\b/g, 'twaalf'],
  [/\bsix\b/g, 'zes'],
  [/\bfour\b/g, 'vier'],
  [/\bfive\b/g, 'vijf'],
  [/\bNine\b/g, 'Negen'],
  [/\bnine\b/g, 'negen'],
  [/\bHis Holiness\b/g, 'Zijne Heiligheid'],
  [/\b[Ee]nthronement van Zijne Heiligheid\b/g, 'Intronisatie van Zijne Heiligheid'],
  [/\bAmerica\b/g, 'Amerika'],
  [/\bGeorgia\b/g, 'Georgië'],
  [/\bSerbia\b/g, 'Servië'],
  [/\bCrimea\b/g, 'de Krim'],
  [/\bPhonecia\b/g, 'Fenicië'],
  [/\bIberia\b/g, 'Iberië'],
  [/\bMesopotamia\b/g, 'Mesopotamië'],
  [/\bBrussels\b/g, 'Brussel'],
  [/\bCarthage\b/g, 'Carthago'],
  [/\bon October (\d+)\b/g, 'op $1 oktober'],
  [/\bOctober (\d+)\b/g, '$1 oktober'],
  [/\bor\b/g, 'of'],
  [/\ba part van\b/g, 'een deel van'],
  [/\bIcons\b/g, 'Iconen'],
  [/\bicons\b/g, 'iconen'],
  [/\bChristos?\b/g, 'Christus'],
  [/\bChrist\b/g, 'Christus'],
  [/\bJesus\b/g, 'Jezus'],
  [/\bHierarchs\b/g, 'Hiërarchen'],
  [/\bMetropolia\b/g, 'Metropolie'],
  [/\bMetropoliet District\b/g, 'Metropolitaanse Regio'],
  [/\bMonastery\b/g, 'Klooster'],
  [/\bDiocese\b/g, 'Bisdom'],
  [/\bCouncils\b/g, 'Concilies'],
  [/\bAll-Russian Church Council\b/g, 'Al-Russisch Kerkelijk Concilie'],
  [/\bCouncil\b/g, 'Concilie'],
  [/\bChurch\b/g, 'Kerk'],
  [/\bHoly Mountain\b/g, 'Heilige Berg'],
  [/\bMountain\b/g, 'Berg'],
  [/\bAll Holy\b/g, 'Alle heilige'],
  [/\bAll Saints\b/g, 'alle heiligen'],
  [/\ball saints\b/g, 'alle heiligen'],
  [/\bsaints\b/g, 'heiligen'],
  [/\bSaints\b/g, 'heiligen'],
  [/\bSaint\b/g, 'H.'],
  [/\bHolly?\b/g, 'Heilige'],
  [/\bHoly\b/g, 'Heilige'],
  [/\bFathers\b/g, 'Vaders'],
  [/\bMothers\b/g, 'Moeders'],
  [/\bMother\b/g, 'Moeder'],
  [/\bBrothers\b/g, 'Broers'],
  [/\bBrother\b/g, 'Broer'],
  [/\bKinsman\b/g, 'Verwant'],
  [/\bAncestors\b/g, 'Voorouders'],
  [/\bcounselor\b/g, 'raadgever'],
  [/\bhealing\b/g, 'genezing'],
  [/\bAppearance\b/g, 'Verschijning'],
  [/\bApparition\b/g, 'Verschijning'],
  [/\bArrival\b/g, 'Aankomst'],
  [/\bRemembrance\b/g, 'Gedachtenis'],
  [/\bMiracle\b/g, 'Wonder'],
  [/\bmiracle\b/g, 'wonder'],
  [/\bGlorification\b/g, 'Heiligverklaring'],
  [/\bRepose\b/g, 'Ontslaping'],
  [/\brepose\b/g, 'rusten'],
  [/\bMartyrdom\b/g, 'Martelaarschap'],
  [/\bTranslation\b/g, 'Overbrenging'],
  [/\bUncovering\b/g, 'Vinding'],
  [/\buncovering\b/g, 'vinding'],
  [/\bFinding\b/g, 'Vinding'],
  [/\bRelics\b/g, 'Relieken'],
  [/\bJerusalem\b/g, 'Jeruzalem'],
  [/\bConstantinople\b/g, 'Constantinopel'],
  [/\bMoscow\b/g, 'Moskou'],
  [/\bRussian\b/g, 'Russische'],
  [/\bRussia\b/g, 'Rusland'],
  [/\bSerbian\b/g, 'Servische'],
  [/\bGeorgians\b/g, 'Georgiërs'],
  [/\bSiberia\b/g, 'Siberië'],
  [/\bAmerican\b/g, 'Amerikaanse'],
  [/\bBosnia\b/g, 'Bosnië'],
  [/\bCentral Asian\b/g, 'Centraal-Aziatische'],
  [/\bSpanish en Portuguese Lands\b/g, 'Spaanse en Portugese Landen'],
  [/\bSpanish\b/g, 'Spaanse'],
  [/\bDeaconess\b/gi, 'Diacones'],
  [/\bdeaconess\b/g, 'diacones'],
  [/\bArchdeacon\b/g, 'Aartsdiaken'],
  [/\bProtomartyr\b/g, 'Protomartelaar'],
  [/\bMartyrs\b/g, 'Martelaren'],
  [/\bMartyr\b/g, 'Martelaar'],
  [/\bMartelaared\b/g, 'Gemartelde'],
  [/\bFast\b/g, 'Vasten'],
  [/\bFeast\b/g, 'Feest'],
  [/\bfeast\b/g, 'feest'],
  [/\bcentury\b/g, 'eeuw'],
  [/\bcenturies\b/g, 'eeuwen'],
  [/\bMost Holy\b/g, 'Allerheiligste'],
  [/\bLord\b/g, 'Heer'],
  [/\bCross\b/g, 'Kruis'],
  [/\bIcon\b/g, 'Icoon'],
  [/\bicon\b/g, 'icoon'],
  [/\bBlind\b/g, 'Blinde'],
  [/\bUnknown\b/g, 'Onbekende'],
  [/\bLesser\b/g, 'Jongere'],
  [/\bNew\b(?! York)/g, 'Nieuwe'],
  [/\bTsar\b/g, 'Tsaar'],
  [/\bRoyal\b/g, 'Koninklijke'],
  [/\bMagdalen\b/g, 'Magdalena'],
  [/\bEighty\b/g, 'Tachtig'],
  [/\bTwenty-three\b/g, 'Drieëntwintig'],
  [/\bTwenty\b/g, 'Twintig'],
  [/\bseven\b/g, 'zeven'],
  [/\bSeven\b/g, 'Zeven'],
  [/\bThree\b/g, 'Drie'],
  [/\bFirst\b/g, 'Eerste'],
  [/\bthe\b/g, 'de'],
  [/\band\b/g, 'en'],
  [/\bwith\b/g, 'met'],
  [/\bto\b/g, 'naar'],
  [/\bfrom\b/g, 'van'],
  [/\bon\b/g, 'op'],
  [/\bat\b/g, 'bij'],
  [/\bby\b/g, 'door'],
  [/\bnamed\b/g, 'genaamd'],
  [/\bwho\b/gi, 'die'],
  [/\bA\.D\./g, 'n.Chr.'],
  [/\bB\.C\./g, 'v.Chr.'],
];

const eeuw = (s: string) =>
  s
    .replace(/\((\d{1,2})(?:st|nd|rd|th) c\.\)/g, '($1e eeuw)')
    .replace(/\b(\d{1,2})(?:st|nd|rd|th) c\./g, '$1e eeuw');

// Grammaticale correcties na het vervangen van de woorden.
const NA: Regel[] = [
  [/\bvan de (Kostbare(?: en (?:Levenschenkende|Levengevende))? Kruis)/g, 'van het $1'],
  [/\bde (Kostbare(?: en (?:Levenschenkende|Levengevende))? Kruis)/g, 'het $1'],
  [/\bvan de Kostbare Hout\b/g, 'van het Kostbare Hout'],
  [/\bvan de Levengevende Kruis\b/g, 'van het Levengevende Kruis'],
  [/\bNederlegging van Kostbare Gewaad\b/g, 'Nederlegging van het Kostbare Gewaad'],
  [/\bDe Eve van\b/g, 'De Vooravond van'],
  [/\bEve van\b/g, 'Vooravond van'],
  [/\bvan de ((?:Eerste|Tweede|Derde|Vierde|Vijfde|Zesde|Zevende|Second|Third|Fourth|Fifth|Sixth|Seventh) Oecumenisch Concilie)/g, 'van het $1'],
  [/\b(\p{Lu}[\p{L}'-]*) (Meer|Rivier|Eiland|Skite|Kluizenarij)\b/gu, (_m: string, naam: string, soort: string) => `${naam}-${soort.toLowerCase()}`],
  [/\bde Diacones\b/g, 'de diacones'],
  [/\b(\p{Lu}[\p{L}'.-]*) Klooster\b/gu, '$1-klooster'],
  [/\bAll Rusland\b/g, 'heel Rusland'],
  [/\bde de\b/g, 'de'],
  [/\bvan de van\b/g, 'van'],
  [/\bvan van\b/g, 'van'],
  [/\bHeilige Heilige\b/g, 'Heilige'],
  [/\bde Heilige Heilige\b/g, 'de Heilige'],
  [/\s+-\s+/g, ' – '],
];

const pas = (s: string, regels: Regel[]) =>
  regels.reduce((t, [re, naar]) => (typeof naar === 'string' ? t.replace(re, naar) : t.replace(re, naar)), s);

// Bijvoeglijke naamwoorden die geen "-icoon"-koppelteken krijgen ("wenende icoon", niet "wenende-icoon").
const BIJVOEGLIJK = /^(De|Het|Een|Icoon|Iconen|Wenende|wenende|Wonderdoende|Spaanse|mirre-vloeiende|Eerbiedwaardige)$/;

/** Zet één naam of titel om naar verzorgd Nederlands. Nederlandse namen blijven ongewijzigd. */
export function verbeterNaam(invoer: string): string {
  if (!invoer) return invoer;
  let s = invoer;
  s = pas(s, TITELS);
  s = pas(s, FRASEN);
  s = pas(s, BEGIN);
  s = pas(s, FEESTEN);
  s = eeuw(s);
  // rechte aanhalingstekens rond een titel → Nederlandse aanhalingstekens
  s = s.replace(/"([^"]+)"/g, '„$1”');
  s = pas(s, WOORDEN);
  s = pas(s, NA);
  // „X” en Y Icoon → X- en Y-icoon;  „X” Icoon → X-icoon;  X Icoon → X-icoon
  s = s.replace(/„([^”]+)” en (\p{Lu}[\p{L}'-]+) Icoon\b/gu, '$1- en $2-icoon');
  s = s.replace(/„([^”]+)” (\([^)]*\) )?Icoon\b/g, (_m, naam: string, jaar?: string) => `${naam}-icoon${jaar ? ' ' + jaar.trim() : ''}`);
  s = s.replace(/\b(\p{Lu}[\p{L}'-]+|wenende|mirre-vloeiende) Icoon\b/gu, (m, naam: string) => (BIJVOEGLIJK.test(naam) ? `${naam} icoon` : `${naam}-icoon`));
  s = ruimOp(s);
  // begon de invoer met een hoofdletter, dan ook de uitvoer (bijv. "Weeping Icon" → "Wenende icoon")
  if (/^\p{Lu}/u.test(invoer)) s = s.charAt(0).toUpperCase() + s.slice(1);
  return s;
}

/** Bevat de tekst nog herkenbaar Engels? (voor controle) */
export const ENGELS = /\b(the|of|and|with|Sunday|Saturday|Icon|Forefeast|Translation|Uncovering|Holy|Saint|Lord|Christ|Our|our|Savior|Saviour|Jesus|Theotokos|Feast|Fast|Fathers|Mothers|Brother|Miracle|Remembrance|Appearance|Monastery|Metropolia|Council|Hierarch|Hierarchs|Cross|Life-Creating|Life-Giving|Universal|Elevation|Baptism|Nativity|Entire)\b/;
